type BlockedPattern = {
  pattern: string;
  exact?: boolean;
  queryParams?: {
    [key: string]: string[];
  };
};

export const blockedPatterns: BlockedPattern[] = [
  {
    pattern: '/vehicles-we-armor/type/armored-suvs',
    queryParams: {
      make: [
        'boxer',
        'bulldog',
        'condor',
        'cuda',
        'cyclone',
        'honda',
        'international',
        'mastiff',
        'omicron',
        'pit-bull',
        'pointer',
        'typhoon',
      ],
    },
  },
  {
    pattern: '/vehicles-we-armor/type/armored-sedans',
    queryParams: {
      make: [
        'boxer',
        'bulldog',
        'cadillac',
        'chevrolet',
        'condor',
        'cuda',
        'cyclone',
        'ford',
        'gmc',
        'honda',
        'hummer',
        'ineos',
        'infiniti',
        'international',
        'jeep',
        'lamborghini',
        'land-rover',
        'lincoln',
        'mastiff',
        'nissan',
        'omicron',
        'pit-bull',
        'pointer',
        'range-rover',
        'rivian',
        'typhoon',
        'volkswagen',
      ],
    },
  },
  {
    pattern: '/vehicles-we-armor/type/armored-pickup-trucks',
    queryParams: {
      make: [
        'audi',
        'bentley',
        'bmw',
        'boxer',
        'bulldog',
        'cadillac',
        'condor',
        'cuda',
        'genesis',
        'honda',
        'ineos',
        'infiniti',
        'international',
        'jeep',
        'lamborghini',
        'land-rover',
        'lexus',
        'lincoln',
        'maybach',
        'mercedes benz',
        'omicron',
        'pointer',
        'range-rover',
        'rolls-royce',
        'volkswagen',
      ],
    },
  },
  {
    pattern: '/vehicles-we-armor/type/armored-law-enforcement',
    queryParams: {
      make: [
        'audi',
        'bentley',
        'bmw',
        'cadillac',
        'chevrolet',
        'condor',
        'genesis',
        'gmc',
        'honda',
        'hummer',
        'ineos',
        'infiniti',
        'international',
        'jeep',
        'lamborghini',
        'land-rover',
        'lexus',
        'lincoln',
        'maybach',
        'nissan',
        'range-rover',
        'rivian',
        'rolls-royce',
        'tesla',
        'toyota',
        'volkswagen',
      ],
    },
  },
  {
    pattern: '/vehicles-we-armor/type/armored-cash-in-transit-cit',
    queryParams: {
      make: [
        'audi',
        'bentley',
        'bmw',
        'boxer',
        'bulldog',
        'cadillac',
        'condor',
        'cuda',
        'cyclone',
        'genesis',
        'honda',
        'hummer',
        'ineos',
        'infiniti',
        'jeep',
        'lamborghini',
        'land-rover',
        'lexus',
        'lincoln',
        'mastiff',
        'maybach',
        'mercedes benz',
        'nissan',
        'omicron',
        'pit-bull',
        'pointer',
        'range-rover',
        'rivian',
        'rolls-royce',
        'tesla',
        'toyota',
        'typhoon',
        'volkswagen',
      ],
    },
  },
  {
    pattern: '/vehicles-we-armor/type/armored-specialty-vehicles',
    queryParams: {
      make: [
        'audi',
        'bentley',
        'bmw',
        'boxer',
        'bulldog',
        'cadillac',
        'chevrolet',
        'cyclone',
        'genesis',
        'gmc',
        'honda',
        'hummer',
        'ineos',
        'infiniti',
        'international',
        'jeep',
        'lamborghini',
        'land-rover',
        'lexus',
        'lincoln',
        'maybach',
        'mercedes benz',
        'nissan',
        'range-rover',
        'rivian',
        'rolls-royce',
        'tesla',
        'typhoon',
        'volkswagen',
      ],
    },
  },
  {
    pattern: '/vehicles-we-armor/type/vans-and-buses',
    queryParams: {
      make: [
        'audi',
        'bentley',
        'bmw',
        'boxer',
        'bulldog',
        'cadillac',
        'condor',
        'cuda',
        'cyclone',
        'genesis',
        'hummer',
        'ineos',
        'infiniti',
        'international',
        'jeep',
        'lamborghini',
        'land-rover',
        'lexus',
        'lincoln',
        'mastiff',
        'maybach',
        'nissan',
        'omicron',
        'pit-bull',
        'range-rover',
        'rivian',
        'rolls-royce',
        'tesla',
        'typhoon',
        'volkswagen',
      ],
    },
  },

  // Static URL patterns (exact matches)
  {
    pattern: '/vehicles-we-armor/150-CIT-International-Navistar-4300-',
    exact: true,
  },
  {
    pattern: '/armored/Lexus/LX570.php',
    exact: true,
  },
  {
    pattern: '/vehicles-we-armor/131-SUV-Chevrolet-Suburban-',
    exact: true,
  },
  {
    pattern:
      '/vehicles-we-armor/140-Sedan-Mercedes-Benz-S-Class-Right-Hand-Drive',
    exact: true,
  },
  {
    pattern: '/vehicles-we-armor/267-Pickup Truck-Ford-F-150',
    exact: true,
  },
  {
    pattern: '/vehicles-we-armor/267-Pickup Truck-Ford-F-150-',
    exact: true,
  },
  {
    pattern: '/vehicles-we-armor/42-Sedan-Mercedes-Benz-S500',
    exact: true,
  },
  {
    pattern: '/vehicles-we-armor/54-Sedan-Toyota-Camry',
    exact: true,
  },
  {
    pattern: '/vehicles-we-armor/179-Police Car-Ford-Taurus-',
    exact: true,
  },
  {
    pattern: '/vehicles-we-armor/345-SUV-Toyota-Sequoia-Hybrid',
    exact: true,
  },
  {
    pattern: '/vehicles-we-armor/345-SUV-Toyota-Sequoia-Hybrid-',
    exact: true,
  },
  {
    pattern: '/vehicles-we-armor/136-SWAT-Pit-Bull-XL®',
    exact: true,
  },
  {
    pattern: '/armored/BMW/X5.php',
    exact: true,
  },
  {
    pattern: '/armored/Audi/q7.php',
    exact: true,
  },
  {
    pattern: '/vehicles-we-armor/179-Police Pursuit Vehicles',
    exact: true,
  },
  {
    pattern: '/available-now/type/armored-cash-in-transit-cit',
    exact: true,
  },
];
