// middleware.js
import { NextResponse } from 'next/server';

export function middleware(request) {
  // Cache static assets for 1 year
  //  if (request.nextUrl.pathname.endsWith('.js')) {
  //     const absoluteUrl = new URL(request.nextUrl.pathname, request.url);
  //     return NextResponse.rewrite(absoluteUrl, {
  //       headers: {
  //         'Cache-Control': 'public, max-age=31536000, immutable',
  //       },
  //     });
  //  }

  // Cache dynamic pages generated by getServerSideProps for 1 hour
  if (
    request.nextUrl.pathname.startsWith('/vehicles-we-armor') ||
    request.nextUrl.pathname.startsWith('/available-now')
  ) {
    const absoluteUrl = new URL(request.nextUrl.pathname, request.url);
    console.log(absoluteUrl);
    return NextResponse.rewrite(absoluteUrl, {
      headers: {
        'Cache-Control': 'public, max-age=3600, must-revalidate',
      },
    });
  }

  // Cache API responses for 1 hour
  //  if (request.nextUrl.pathname.startsWith('/api/')) {
  //     const absoluteUrl = new URL(request.nextUrl.pathname, request.url);
  //     return NextResponse.rewrite(absoluteUrl, {
  //       headers: {
  //         'Cache-Control': 'public, max-age=3600, must-revalidate',
  //       },
  //     });
  //  }

  return NextResponse.next();
}
